project:
  type: website

website:
  title: "web"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents: auto

format:
  html:
    theme:
      - brand
    css: style.scss
    toc: true

brand: _brand.yml

filters:
  - highlight-text


    